#!/bin/sh
# https://github.com/shyiko/ktlint pre-commit hook
git diff --name-only --cached --relative | grep '\.kt[s"]\?$' | xargs ktlint --relative .
# shellcheck disable=SC2181
if [ $? -ne 0 ]; then exit 1; fi